# Generated by Django 5.1.2 on 2024-11-25 05:06

import apps.transactions.models
import django.core.validators
from decimal import Decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_transfer_reasons_and_migrate_data(apps, schema_editor):
    """
    Crea los motivos de transferencia y migra los datos existentes
    """
    TransferReason = apps.get_model('transactions', 'TransferReason')
    
    # Mapeo de los antiguos valores a los nuevos
    reason_mapping = {
        'PAYMENT': ('Pago de servicios', 'Pago por servicios prestados'),
        'LOAN': ('Préstamo', 'Préstamo de dinero'),
        'GIFT': ('Regalo', 'Regalo o donación'),
        'RENT': ('Alquiler', 'Pago de alquiler'),
        'SALARY': ('Salario', 'Pago de salario'),
        'OTHER': ('Otro', 'Otros motivos'),
    }
    
    # Crear los motivos
    for old_reason, (name, description) in reason_mapping.items():
        TransferReason.objects.create(
            name=name,
            description=description,
            is_active=True
        )


def reverse_transfer_reasons_and_data(apps, schema_editor):
    """
    Revierte la migración de los motivos de transferencia
    """
    TransferReason = apps.get_model('transactions', 'TransferReason')
    TransferReason.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        # Crear el modelo TransferReason
        migrations.CreateModel(
            name='TransferReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Motivo de transferencia',
                'verbose_name_plural': 'Motivos de transferencia',
                'ordering': ['name'],
            },
        ),
        
        # Crear el modelo Transaction
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Ingreso de dinero'), ('TRANSFER', 'Transferencia')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destino')),
                ('reason', models.ForeignKey(default=apps.transactions.models.TransferReason.get_default_reason, on_delete=django.db.models.deletion.PROTECT, to='transactions.transferreason', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        
        # Ejecutar la migración de datos
        migrations.RunPython(
            create_transfer_reasons_and_migrate_data,
            reverse_transfer_reasons_and_data,
        ),
    ]
